### ISSUE TITLE
document coag eqs

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#28]
- [x] add documentation, references re pr #27 
- [x] consider moving calcs to own class/module (distinguish between objects and dynamic entities)
- [x] ensure calcs return correct values 
- [x] improve tests by adding dimensions

**Comment by wkchuang** [comment]
Check out the two types of dimension checking that are currently in `particle.py` and `particle_test.py`. The first is the decorator above each function in `particle.py` that enforces input/output units. The second is the assertion statements in `particle_test.py` that check for the type of units, but not the units themselves (e.g. checks for mass instead of kilograms). The second is a bit redundant and was written before the decorator units checks, but may still prove useful as a sanity check. Feel free to change it around!

**Comment by ngam** [comment]
> Feel free to change it around

No, I like your tests! I will check it out. By dimensions, I mean matrix/tensor dimensions here, e.g. `(3, 3, 3)` vs `(3, 3, 1)`. It will become clearer as we do coagulation calculations, via a coagulation kernel, which will be `(N, N)`. I don't believe you've added such a thing yet, but I will check again :)
