### ISSUE TITLE
thoughts on (re)naming the unit registry

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#60]
I will leave this up mainly to @wkchuang; we need to have consistent and clear naming scheme throughout the whole package. Having the unit registry be simply `u` might be a bit confusing. How about something like `unit` or `units` or `unit_reg` or something along these lines? Nothing urgent, but let's keep this in mind.

We should ideally also outline a general naming scheme that we can follow throughout. We need to find a balance of descriptiveness (e.g. `this_is_really_this`) and convenience (i.e. shorter and easy to interpret).

Maybe we can open this as a discussion topic later as well.

**Comment by wkchuang** [comment]
I gave this some consideration when first implementing units. Choosing `u` over `unit` or `units` was because 

- Seeing u.kg or u.Pa strongly hints at units 
- Learning that u = units for the entire package is not difficult when it is ubiquitous throughout the package, and its usage makes it even more clear: it comes after a number, and the variable names signal the functionality of `u` (particle_radius has a u.m, particle_mass has a u.kg). Most people who would use this package are used to units. 
- Some variables and constants have a lot of units. Having `unit` before each unit adds no value, makes it unnecessarily long and de-emphasizes the important information--the actual unit itself, which tends to be only 1 or 2 letters.

**Comment by ngam** [comment]
Thanks!

**Comment by ngam** [comment]
I will close this for now. I agree with your point above. Note, I moved the unit registry to a new location (to the top-most __init__):

https://github.com/uncscode/particula/blob/6ecb6a1a3a4b8e56c1a5b0e1f94f38638c64ca86/particula/__init__.py#L16-L20
